export const state = {
  adminKey: "",
  paused: false,
  refreshMs: 5000,
  timer: null,
  view: "overview",
  timeRange: "30m",
  requestsPage: 0,
  requestFilters: {
    status: "",
  },
  configTab: "routes",
  statisticsView: "usage",
  usageStatisticsRange: "all",
  usageStatisticsMetric: "tokens",
  usageStatisticsBreakdown: "model",
  usageStatisticsBreakdownSort: "tokens",
  usageStatisticsBreakdownPage: 0,
  usageStatisticsCustomStart: "",
  usageStatisticsCustomEnd: "",
  usageStatisticsFilters: {
    model: "",
    provider: "",
    client_format: "",
  },
  usageStatisticsLoading: false,
  usageStatisticsLoadSeq: 0,
  modelUsageRange: "7d",
  modelUsageQuery: "",
  modelUsageSort: "calls",
  modelUsagePage: 0,
  modelUsageLoading: false,
  selectedRequestIds: new Set(),
  allMatchingSelected: false,
  trafficChartMode: "requests",
  providersPage: 0,
  configProvidersPage: 0,
  modelRoutesPage: 0,
  providerModelMapPage: 0,
  auditPage: 0,
  forceConfigRender: false,
  forceModelRoutesRender: false,
  forcePolicyRender: false,
  forceFailurePoliciesRender: false,
  forceProvidersRender: false,
  forceModelCapsRender: false,
  forceTimeseriesFetch: false,
  forceRequestsFetch: false,
  openProviderDetails: new Set(),
  openProviderEditors: new Set(),
  providerDrawerName: "",
  providerDrawerTab: "overview",
  detailDrawerReturn: null,
  modelDrawerMode: "summary",
  providerFilters: {
    search: "",
    format: "",
    status: "",
    keys: "",
  },
  providerModelFilters: {
    search: "",
    status: "",
  },
  providerModelDrafts: {},
  confirmResolve: null,
  confirmLastFocus: null,
  keyProbes: {},
  keyProbeInFlight: {},
  data: {
    metrics: null,
    metricsFull: null,
    status: null,
    routing: null,
    config: null,
    timeseries: null,
    requests: null,
    overlay: null,
    providerActivity: null,
    usageStatistics: null,
    usageStatisticsDimensions: null,
    modelUsage: null,
    modelUsageDetail: null,
    // Bumped on every successful refresh so derived caches (e.g. the model
    // capability items memo) can invalidate in O(1) without deep-comparing data.
    version: 0,
  },
};
