from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Dict, Optional

from .common import unwrap_custom_tool_arguments
from .errors import ConversionError
from .model import ConversionContext


def original_tool_name(context: Optional[ConversionContext], wire_name: str) -> str:
    """Return the client-visible tool name for a converted upstream name."""
    if context is None:
        return wire_name
    return context.tool_name_to_original.get(wire_name, wire_name)


def is_custom_tool(context: Optional[ConversionContext], wire_name: str) -> bool:
    if context is None:
        return False
    original = original_tool_name(context, wire_name)
    return wire_name in context.custom_tool_names or original in context.custom_tool_names


class CustomToolArgumentDecoder:
    """Incrementally decode the string in a ``{"content": ...}`` wrapper.

    Chat and Messages providers expose Responses custom tools as ordinary JSON
    function tools.  Their argument fragments may split at every byte, including
    in the middle of a JSON escape.  This decoder only emits complete decoded
    characters, so callers never have to parse each fragment as standalone JSON.
    """

    _SIMPLE_ESCAPES = {
        '"': '"',
        "\\": "\\",
        "/": "/",
        "b": "\b",
        "f": "\f",
        "n": "\n",
        "r": "\r",
        "t": "\t",
    }

    def __init__(self) -> None:
        self._probe = ""
        self._started = False
        self._done = False
        self._escape = False
        self._unicode_digits: Optional[str] = None
        self._pending_high_surrogate: Optional[int] = None

    @property
    def done(self) -> bool:
        return self._done

    def feed(self, fragment: str) -> str:
        if not fragment or self._done:
            return ""
        if not self._started:
            self._probe += fragment
            start = self._find_content_string_start(self._probe)
            if start is None:
                return ""
            fragment = self._probe[start:]
            self._probe = ""
            self._started = True

        out: list[str] = []
        for char in fragment:
            if self._done:
                break
            if self._unicode_digits is not None:
                if char.lower() not in "0123456789abcdef":
                    # Invalid JSON. Stop emitting; finish() will return the raw
                    # arguments instead of inventing custom-tool input.
                    self._done = True
                    break
                self._unicode_digits += char
                if len(self._unicode_digits) == 4:
                    self._append_codepoint(out, int(self._unicode_digits, 16))
                    self._unicode_digits = None
                    self._escape = False
                continue
            if self._escape:
                if char == "u":
                    self._unicode_digits = ""
                    continue
                mapped = self._SIMPLE_ESCAPES.get(char)
                if mapped is None:
                    self._done = True
                    break
                self._flush_pending_high(out)
                out.append(mapped)
                self._escape = False
                continue
            if char == "\\":
                self._escape = True
                continue
            if char == '"':
                self._flush_pending_high(out)
                self._done = True
                break
            self._flush_pending_high(out)
            out.append(char)
        return "".join(out)

    @staticmethod
    def _find_content_string_start(value: str) -> Optional[int]:
        # Tool wrappers generated by this project contain a top-level content
        # key. Keep the recogniser deliberately narrow; if a provider emits a
        # different shape, finish() preserves the raw value.
        marker = '"content"'
        key_at = value.find(marker)
        if key_at < 0:
            return None
        pos = key_at + len(marker)
        while pos < len(value) and value[pos].isspace():
            pos += 1
        if pos >= len(value) or value[pos] != ":":
            return None
        pos += 1
        while pos < len(value) and value[pos].isspace():
            pos += 1
        if pos >= len(value) or value[pos] != '"':
            return None
        return pos + 1

    def _append_codepoint(self, out: list[str], value: int) -> None:
        if 0xD800 <= value <= 0xDBFF:
            self._flush_pending_high(out)
            self._pending_high_surrogate = value
            return
        if 0xDC00 <= value <= 0xDFFF and self._pending_high_surrogate is not None:
            high = self._pending_high_surrogate
            self._pending_high_surrogate = None
            out.append(chr(0x10000 + ((high - 0xD800) << 10) + (value - 0xDC00)))
            return
        self._flush_pending_high(out)
        out.append(chr(value))

    def _flush_pending_high(self, out: list[str]) -> None:
        if self._pending_high_surrogate is not None:
            # Preserve a malformed standalone surrogate deterministically.
            out.append("\ufffd")
            self._pending_high_surrogate = None


@dataclass
class StreamingToolCall:
    """Protocol-neutral state for one streamed tool call."""

    source_index: int
    context: Optional[ConversionContext] = None
    call_id: str = ""
    wire_name: str = ""
    arguments: str = ""
    _custom_decoder: Optional[CustomToolArgumentDecoder] = field(default=None, init=False, repr=False)

    @property
    def name(self) -> str:
        return original_tool_name(self.context, self.wire_name)

    @property
    def custom(self) -> bool:
        return is_custom_tool(self.context, self.wire_name)

    def update(self, *, call_id: str = "", name: str = "") -> None:
        if call_id:
            self.call_id = call_id
        if name:
            was_custom = self.custom
            self.wire_name = name
            if self.custom and not was_custom and self.arguments:
                self._decoder().feed(self.arguments)

    def append_arguments(self, fragment: str) -> str:
        if not fragment:
            return ""
        self.arguments += fragment
        if not self.custom:
            return fragment
        return self._decoder().feed(fragment)

    def custom_input(self) -> str:
        return unwrap_custom_tool_arguments(self.arguments)

    def validate_arguments(self) -> None:
        if self.custom:
            return
        try:
            parsed = json.loads(self.arguments or "{}")
        except (TypeError, ValueError, json.JSONDecodeError) as exc:
            raise ConversionError(
                f"streamed tool arguments contain invalid JSON: {exc}",
                code="invalid_tool_arguments",
                field=f"stream.tool_calls[{self.source_index}].arguments",
                details={"raw_arguments": self.arguments},
            ) from exc
        if not isinstance(parsed, dict):
            raise ConversionError(
                "streamed tool arguments must decode to a JSON object",
                code="invalid_tool_arguments",
                field=f"stream.tool_calls[{self.source_index}].arguments",
                details={"raw_arguments": self.arguments},
            )

    def responses_item(self, *, status: str, item_id: str) -> Dict[str, object]:
        item: Dict[str, object] = {
            "id": item_id,
            "type": "custom_tool_call" if self.custom else "function_call",
            "call_id": self.call_id or item_id,
            "name": self.name or "unknown",
            "status": status,
        }
        if self.custom:
            item["input"] = self.custom_input() if status == "completed" else ""
        else:
            item["arguments"] = self.arguments if status == "completed" else ""
        return item

    def _decoder(self) -> CustomToolArgumentDecoder:
        if self._custom_decoder is None:
            self._custom_decoder = CustomToolArgumentDecoder()
        return self._custom_decoder


class ToolCallRegistry:
    """Stable source-index registry shared by the stream adapters."""

    def __init__(self, context: Optional[ConversionContext] = None) -> None:
        self.context = context
        self._calls: Dict[int, StreamingToolCall] = {}

    def get(self, index: int) -> StreamingToolCall:
        if index not in self._calls:
            self._calls[index] = StreamingToolCall(source_index=index, context=self.context)
        return self._calls[index]

    def items(self):
        return self._calls.items()
